# Generated by Django 4.0.5 on 2022-06-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_note_updated_on'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notebook',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_name_per_user'),
        ),
    ]
